name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make -C build
    - name: make check
      run: make -C build check
    - name: make distcheck
      run: make -C build distcheck
