name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt update -y
    - name: install deps
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev -y
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make -C build
    - name: make check
      run: make -C build check
    - name: make distcheck
      run: make -C build distcheck
